project_id = "txkivfkeoxbncqleehia"

[functions.generate-post]
verify_jwt = false

[functions.analyze-watch]
verify_jwt = false

[functions.generate-calendar]
verify_jwt = false

[functions.perplexity-watch]
verify_jwt = false
